website:
  sidebar:
  - contents:
    - docs/reference/bedrock-ge-api/index.qmd
    - contents:
      - docs/reference/bedrock-ge-api/gi.mapper.map_to_brgi_db.qmd
      - docs/reference/bedrock-ge-api/gi.db_operations.merge_dbs.qmd
      - docs/reference/bedrock-ge-api/gi.geospatial.create_brgi_geodb.qmd
      - docs/reference/bedrock-ge-api/gi.geospatial.create_location_geodf.qmd
      - docs/reference/bedrock-ge-api/gi.geospatial.create_lon_lat_height_geodf.qmd
      - docs/reference/bedrock-ge-api/gi.geospatial.interpolate_gi_geometry.qmd
      - docs/reference/bedrock-ge-api/gi.geospatial.interpolate_3d.qmd
      - docs/reference/bedrock-ge-api/gi.geospatial.substring_3d.qmd
      section: Map to Bedrock GI
    - contents:
      - docs/reference/bedrock-ge-api/gi.write.write_brgi_db_to_file.qmd
      - docs/reference/bedrock-ge-api/gi.validate.check_foreign_key.qmd
      - docs/reference/bedrock-ge-api/gi.io_utils.geodf_to_df.qmd
      - docs/reference/bedrock-ge-api/gi.io_utils.brgi_db_to_dfs.qmd
      - docs/reference/bedrock-ge-api/gi.io_utils.open_text_data_source.qmd
      - docs/reference/bedrock-ge-api/gi.io_utils.detect_encoding.qmd
      - docs/reference/bedrock-ge-api/gi.io_utils.coerce_string.qmd
      section: IO
    - contents:
      - docs/reference/bedrock-ge-api/gi.ags.ags_to_brgi_db_mapping.qmd
      - docs/reference/bedrock-ge-api/gi.ags4.ags4_to_dfs.qmd
      - docs/reference/bedrock-ge-api/gi.ags3.ags3_to_brgi_db_mapping.qmd
      - docs/reference/bedrock-ge-api/gi.ags3.ags3_to_dfs.qmd
      - docs/reference/bedrock-ge-api/gi.ags_schemas.check_ags_proj_group.qmd
      section: AGS
    id: docs/reference/bedrock-ge-api
  - id: dummy-sidebar
