project:
  type: website
  resources:
    - "public/**/*"
  preview:
    port: 4200
  
website:
  title: "Bedrock"
  description: "Bedrock, the Open Source Foundation for Geotechnical Engineering"
  image: "public/Bedrock_inCircle.png"
  favicon: "public/favicon.ico"
  open-graph: 
    title: "Bedrock"
    description: "Bedrock, the Open Source Foundation for Geotechnical Engineering"
    image: "public/Bedrock_TextRight.png"
    locale: en_US
  twitter-card: true
  google-analytics:
    tracking-id: "G-JH73EGWYL6"
    anonymize-ip: true
  site-url: https://bedrock.engineer
  repo-url: https://github.com/bedrock-engineer/bedrock-web
  issue-url: https://github.com/bedrock-engineer/bedrock-ge/issues/new/choose
  repo-actions: [source, edit, issue]
  
  # page-footer: 
  #   right:
  #     - icon: github
  #       href: https://github.com/bedrock-gi/bedrock-gi
  #     - icon: linkedin
  #       href: https://www.linkedin.com/company/bedrock-gi/

  page-navigation: true
  bread-crumbs: true
  navbar:
    logo: "public/Bedrock.png"
    logo-alt: "Bedrock"
    left:
      - text: "Docs"
        href: docs/index.qmd
      - text: "Articles"
        href: articles.qmd
      # - text: "Community"
      #   href: community.qmd
      - text: "Help"
        menu:
          - text: "Report a Bug"
            icon: "bug"
            href: "https://github.com/bedrock-engineer/bedrock-ge/issues"
          - text: "Ask Bedrock a Question"
            icon: "chat-right-text"
            href: "https://github.com/orgs/bedrock-engineer/discussions"
          - text: "Professional Support"
            icon: "person-raised-hand"
            href: "/professional-support"
          # - text: "FAQ"
          #   icon: "question-circle"
          #   href: faq.qmd
      - text: "About"
        href: about.qmd
    tools:
      - icon: github
        href: https://github.com/bedrock-engineer/bedrock-ge
        text: Bedrock's GitHub
      - icon: linkedin
        href: https://www.linkedin.com/company/bedrock-engineer
        text: Bedrock's LinkedIn

  sidebar:
    - id: docs
      style: "floating"
      contents:
        - docs/index.qmd
        - docs/getting-started.qmd
        - docs/tutorials/index.qmd
        - docs/how-to/index.qmd
        - section: "Explanations"
          href: docs/explanations/index.qmd
          contents:
            - docs/explanations/gi/index.qmd
            - docs/explanations/gi/soil-classification.qmd
        - section: "Reference"
          href: docs/reference/index.qmd
          contents:
            - docs/reference/glossary/index.qmd
            - section: "`bedrock-ge` API"
              href: docs/reference/bedrock-ge-api/index.qmd
              contents:
                - contents:
                  - docs/reference/bedrock-ge-api/gi.mapper.map_to_brgi_db.qmd
                  - docs/reference/bedrock-ge-api/gi.db_operations.merge_dbs.qmd
                  - docs/reference/bedrock-ge-api/gi.geospatial.create_brgi_geodb.qmd
                  - docs/reference/bedrock-ge-api/gi.geospatial.create_location_geodf.qmd
                  - docs/reference/bedrock-ge-api/gi.geospatial.create_lon_lat_height_geodf.qmd
                  - docs/reference/bedrock-ge-api/gi.geospatial.interpolate_gi_geometry.qmd
                  - docs/reference/bedrock-ge-api/gi.geospatial.interpolate_3d.qmd
                  - docs/reference/bedrock-ge-api/gi.geospatial.substring_3d.qmd
                  section: Map to Bedrock GI
                - contents:
                  - docs/reference/bedrock-ge-api/gi.write.write_brgi_db_to_file.qmd
                  - docs/reference/bedrock-ge-api/gi.validate.check_foreign_key.qmd
                  - docs/reference/bedrock-ge-api/gi.io_utils.geodf_to_df.qmd
                  - docs/reference/bedrock-ge-api/gi.io_utils.brgi_db_to_dfs.qmd
                  - docs/reference/bedrock-ge-api/gi.io_utils.open_text_data_source.qmd
                  - docs/reference/bedrock-ge-api/gi.io_utils.detect_encoding.qmd
                  - docs/reference/bedrock-ge-api/gi.io_utils.coerce_string.qmd
                  section: IO
                - contents:
                  - docs/reference/bedrock-ge-api/gi.ags.ags_to_brgi_db_mapping.qmd
                  - docs/reference/bedrock-ge-api/gi.ags4.ags4_to_dfs.qmd
                  - docs/reference/bedrock-ge-api/gi.ags3.ags3_to_brgi_db_mapping.qmd
                  - docs/reference/bedrock-ge-api/gi.ags3.ags3_to_dfs.qmd
                  - docs/reference/bedrock-ge-api/gi.ags_schemas.check_ags_proj_group.qmd
                  section: AGS
            - docs/reference/bibliography/index.qmd
  
  search:
    type: textbox
    show-item-context: true

language: 
  search-box-placeholder: Search

quartodoc:
  # the name used to import the package you want to create reference docs for
  package: bedrock_ge
  parser: google
  dir: docs/reference/bedrock-ge-api
  sidebar: _quartodoc-sidebar.yml

  sections:
    - title: Map to Bedrock GI
      desc: Functions for mapping any type of GI data to the Bedrock GI geospatial database schema.
      contents:
        - gi.mapper.map_to_brgi_db
        - gi.db_operations.merge_dbs
        - gi.geospatial.create_brgi_geodb
        - gi.geospatial.create_location_geodf
        - gi.geospatial.create_lon_lat_height_geodf
        - gi.geospatial.interpolate_gi_geometry
        - gi.geospatial.interpolate_3d
        - gi.geospatial.substring_3d

    - title: IO
      desc: Validate Bedrock GI databases
      contents: 
        - gi.write.write_brgi_db_to_file
        - gi.validate.check_foreign_key
        - gi.io_utils.geodf_to_df
        - gi.io_utils.brgi_db_to_dfs
        - gi.io_utils.open_text_data_source
        - gi.io_utils.detect_encoding
        - gi.io_utils.coerce_string
    
    - title: AGS
      desc: Functions for creating Bedrock GI mapping objects from AGS files.
      contents:
        - gi.ags.ags_to_brgi_db_mapping
        - gi.ags4.ags4_to_dfs
        - gi.ags3.ags3_to_brgi_db_mapping
        - gi.ags3.ags3_to_dfs
        - gi.ags_schemas.check_ags_proj_group

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    toc: true
    toc-depth: 2
    link-external-icon: true
    link-external-newwindow: true
    jupyter: python3
    code-copy: true
    code-fold: true
    code-annotations: hover
    include-in-header:
      - text: <link rel="icon" href="./public/Bedrock.svg" type="image/svg+xml">

execute:
  freeze: auto
