---
title: "About"
image: https://avatars.githubusercontent.com/u/50735562
about:
  template: solana
  links:
    - icon: linkedin
      text: Bedrock LinkedIn
      href: https://www.linkedin.com/company/bedrock-gi/
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com/in/joost-gevaert
    - icon: github
      text: Github
      href: https://github.com/JoostGevaert
format:
  html:
    toc: false
    repo-actions: false
---

## Joost Gevaert

Hi, I'm Joost Gevaert 👋

I studied geotechnical engineering and applied geophysics and then worked for [Arup](https://www.arup.com/) for 4 years as a geotechnical engineer a computational designer.

During my time at Arup I worked a lot on bringing computational design into the world of geotechnical engineering, and on [bridging the gaps between geotechnical engineering and structural engineering](https://www.linkedin.com/posts/joost-gevaert_lightbim-lightbim-lightbim-activity-7234726439835549697-3xdO).

Bedrock is the Free and Open Source Software (FOSS) that I wish existed when I worked as a geotechnical engineer at Arup.

> Computational design is a field that involves the use of computer algorithms, simulations, and data analysis to support and enhance the design process. It enables designers to explore vast design spaces, to find solutions to complex design problems, and to make informed decisions based on data-driven insights.  
> Source: [Computational design | Arup](https://www.arup.com/services/computational-and-parametric-design/)

## Jules Blom

Hi, my name is Jules. I studied Applied Geoscience (Petroleum Engineering Reservoir Geology) but frustration with technical software led me to learn to code and as a result, I mostly worked in software development.

Over the past 5 years, I've worked on data-rich applications across various domains, specifically frontend development.
My primary interest is figuring out how to build tools for more thoughtful display and processing of technical information, geoscience in particular.

