---
title: Spatial Reference Systems
---

## SRS Types

### Vertical SRS (1D) - (Height)

- [EPSG:5709](https://epsg.io/5709): NAP Height - [Normaal Amsterdams Peil](https://epsg.io/5109-datum) Height
- [EPSG:5701](https://epsg.io/5701): ODN Height - [Ordnance Datum Newlyn](https://epsg.io/5101-datum) Height
- [EPSG:5738](https://epsg.io/5738): HKPD Height - [Hong Kong Principal Datum](https://epsg.io/5135-datum) Height
- [EPSG:7839](https://epsg.io/7839): NZVD2016 Height - [New Zealand Vertical Datum 2016](https://epsg.io/1169-datum) Height

### Geographic (2D) - (Lat, Lon)

- [EPSG:4326](https://epsg.io/4326): WGS84 - World Geodetic System 1984, used in GPS

### Geographic (3D) - (Lat, Lon, Ellipsoidal Height)

- [EPSG:4979](https://epsg.io/4979): WG84

### Projected (Easting, Northing)

- [EPSG:3857](https://epsg.io/3857): "Web Mercator" - WGS 84 / Pseudo-Mercator -- Spherical Mercator, Google Maps, OpenStreetMap, Bing, ArcGIS, ESRI
- [EPSG:28992](https://epsg.io/28992): Amersfoort / RD New -- Netherlands - Holland - Dutch
- [EPSG:27700](https://epsg.io/27700): OSGB36 / British National Grid -- United Kingdom Ordnance Survey
- [EPSG:29902](https://epsg.io/29902): TM65 / Irish Grid -- Ireland
- [EPSG:2326](https://epsg.io/2326): Hong Kong 1980 Grid System
- [EPSG:2193](https://epsg.io/2193): NZGD2000 / New Zealand Transverse Mercator 2000 -- New Zealand Transverse Mercator (NZTM)

### Compound (Easting, Northing, Orthometric Height | Lat, Lon, Orthometric Height)

- [EPSG:9518](http://epsg.io/9518): WGS 84 + EGM2008 height
- [EPSG:7415](https://epsg.io/7415): Amersfoort / RD New + NAP height (Easting, Northing, Orthometric Height)
- [EPSG:7405](https://epsg.io/7405): OSGB36 / British National Grid + ODN height (Easting, Northing, Orthometric Height)
- [EPSG:9528](https://epsg.io/9528): NZGD2000 + NZVD2016 height (Lat, Lon, Orthometric Height)

### Geocentric, i.e. ECEF (X, Y, Z)

- [EPSG:4978](https://epsg.io/4978): WGS 84
