# gi.concatenate.concatenate_databases { #bedrock_ge.gi.concatenate.concatenate_databases }

```python
gi.concatenate.concatenate_databases(db1, db2)
```

Concatenates two dictionaries of DataFrames into one dict of DataFrames.

The function concatenates the pandas DataFrames of the second dict of
DataFrames to the first dict of DataFrames for the keys they have in common.
Keys that are unique to either dictionary will be included in the final
concatenated dictionary.

## Parameters {.doc-section .doc-section-parameters}

| Name   | Type                      | Description                                         | Default    |
|--------|---------------------------|-----------------------------------------------------|------------|
| db1    | Dict\[str, pd.DataFrame\] | A dictionary of pandas DataFrames, i.e. a database. | _required_ |
| db2    | Dict\[str, pd.DataFrame\] | A dictionary of pandas DataFrames, i.e. a database. | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type                      | Description                                     |
|--------|---------------------------|-------------------------------------------------|
| dict   | Dict\[str, pd.DataFrame\] | A dictionary of concatenated pandas DataFrames. |