# gi.gis_geometry.calculate_location_gis_geometry { #bedrock_ge.gi.gis_geometry.calculate_location_gis_geometry }

```python
gi.gis_geometry.calculate_location_gis_geometry(brgi_location, crs)
```

Calculates GIS geometry for a set of Ground Investigation locations.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type                                    | Description                                                        | Default    |
|---------------|-----------------------------------------|--------------------------------------------------------------------|------------|
| brgi_location | Union\[pd.DataFrame, gpd.GeoDataFrame\] | The GI locations to calculate GIS geometry for.                    | _required_ |
| crs           | pyproj.CRS                              | The Coordinate Reference System (CRS) to use for the GIS geometry. | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type             | Description                                                                                                                                                                                                                                                                                                                                                                                                                 |
|--------|------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|        | gpd.GeoDataFrame | gpd.GeoDataFrame: The GIS geometry for the given GI locations, with additional columns: - longitude: The longitude of the location in the WGS84 CRS. - latitude: The latitude of the location in the WGS84 CRS. - wgs84_ground_level_height: The height of the ground level of the location in the WGS84 CRS. - elevation_at_base: The elevation at the base of the location. - geometry: The GIS geometry of the location. |