# gi.gis_geometry.calculate_in_situ_gis_geometry { #bedrock_ge.gi.gis_geometry.calculate_in_situ_gis_geometry }

```python
gi.gis_geometry.calculate_in_situ_gis_geometry(brgi_in_situ, brgi_location, crs)
```

Calculates GIS geometry for a set of Ground Investigation in-situ data.

## Parameters {.doc-section .doc-section-parameters}

| Name          | Type                                    | Description                                          | Default    |
|---------------|-----------------------------------------|------------------------------------------------------|------------|
| brgi_in_situ  | Union\[pd.DataFrame, gpd.GeoDataFrame\] | The in-situ data to calculate GIS geometry for.      | _required_ |
| brgi_location | Union\[pd.DataFrame, gpd.GeoDataFrame\] | The location data to merge with the in-situ data.    | _required_ |
| crs           | CRS                                     | The Coordinate Reference System of the in-situ data. | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type             | Description                                                                             |
|--------|------------------|-----------------------------------------------------------------------------------------|
|        | gpd.GeoDataFrame | gpd.GeoDataFrame: The GIS geometry for the given in-situ data, with additional columns: |
|        | gpd.GeoDataFrame | - elevation_at_top: The elevation at the top of the in-situ data.                       |
|        | gpd.GeoDataFrame | - elevation_at_base: The elevation at the base of the in-situ data.                     |
|        | gpd.GeoDataFrame | - geometry: The GIS geometry of the in-situ data.                                       |