# gi.mapper.map_to_brgi_db { #bedrock_ge.gi.mapper.map_to_brgi_db }

```python
gi.mapper.map_to_brgi_db(brgi_db_mapping)
```

Creates a Bedrock GI Database for a single project from a BedrockGIMapping.

This function takes a BedrockGIDatabaseMapping, which contains various table mappings
for project, location, in-situ tests, samples, lab tests, and other tables, and
converts it into a BedrockGIDatabase object. It creates pandas DataFrames for each
table, validates them against their respective schemas, and constructs the final
BedrockGIDatabase object.

## Example {.doc-section .doc-section-example}

```python
from pyproj import CRS
from bedrock_ge.gi.mapping_models import BedrockGIMapping

brgi_db_mapping = BedrockGIMapping(
    ProjectTableMapping={
        "data": {
            "project_name: "Test Project",
            "project_description": "Project description. Add more data about the project here if you please."
        }
        "project_id": "project-1",
        "horizontal_crs": CRS("EPSG:2193"),
        "vertical_crs": CRS("EPSG:7839"),
    },
    LocationTableMapping={
        "data": location_df,
        "location_id_column": "LocationID",
        "easting_column": "Easting",
        "northing_column": "Northing",
        "ground_level_elevation_column": "GroundLevel",
        "depth_to_base_column": "FinalDepth",
    },
    InSituTestTableMapping=[
        {
            "table_name": "Geol",
            "data": geology_df,
            "location_id_column": "LocationID",
            "depth_to_top_column": "from",
            "depth_to_base_column": "to",
        },
        {
            "table_name": "SPT",
            "data": spt_df,
            "location_id_column": "LocationID",
            "depth_to_top"column": "from",
        }
    ],
    SampleTableMapping=None,
    LabTestTableMapping=[],
    OtherTable=[],
)
```

## Parameters {.doc-section .doc-section-parameters}

| Name            | Type             | Description                                                                         | Default    |
|-----------------|------------------|-------------------------------------------------------------------------------------|------------|
| brgi_db_mapping | BedrockGIMapping | The mapping object containing GI data and metadata for mapping to Bedrock's schema. | _required_ |

## Returns {.doc-section .doc-section-returns}

| Name   | Type              | Description                                                                              |
|--------|-------------------|------------------------------------------------------------------------------------------|
|        | BedrockGIDatabase | The transformed Bedrock GI database containing validated DataFrames for each table type. |